# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "➜" symbol in the prompt with "❯"
[character]      # The name of the module we are confguring is "character"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold green)"

[aws]
disabled = true

[directory]
truncation_length = 2

[package]
disabled = true

[gcloud]
disabled = true
